### ISSUE TITLE
How to separate sentences when there is no punctuation?

### ISSUE THREAD

**Issue by asasas234** [nipunsadvilkar/pySBD#124]
for example:
```
how are you fine thank you and you
```
I hope to be able to divide the above words into 3 sentences.
1. how are you
2. fine thank you
3. and you

**Comment by kongyurui** [comment]
Probably need some sort of machine learning module to do that kind of sentence breaking.  pySBD uses heuristics based on punctuation.

**Comment by nipunsadvilkar** [comment]
Yes pySBD is rules based and heuristics module so wont work on use-cases where there not all any punctuation.
