### ISSUE TITLE
Shouldn't colons cause a sentence split?

### ISSUE THREAD

**Issue by RuABraun** [nipunsadvilkar/pySBD#44]
They currently don't:

```
>>> s = 'Tomorrow I will do the greatest thing ever: Become a god.'
>>> seg.segment(s)
['Tomorrow I will do the greatest thing ever: Become a god.']
>>> s = 'The best player of the city: Zob Ahan F.C. and Sepahan F.C..'
>>> seg.segment(s)
['The best player of the city: Zob Ahan F.C. and Sepahan F.C..']
```

**Comment by nipunsadvilkar** [comment]
@RuABraun: not by default design choice of `pysbd` & `pragmatic_segmenter` . Still, if you wish to add `:` then update it at the of `SENTENCE_BOUNDARY_REGEX` - `\S.*?[。．.:！!?？ȸȹ☉☈☇☄]`.


https://github.com/nipunsadvilkar/pySBD/blob/f3d0ae4290a51288475472fa7e367854065337b9/pysbd/lang/common/numbers.py#L10

**Comment by RuABraun** [comment]
Thanks
