### ISSUE TITLE
Text surrounded by quotes seems to not get segmented?

### ISSUE THREAD

**Issue by RuABraun** [nipunsadvilkar/pySBD#45]
```
>>> s = '"I just love doing this sort of thing. It\'s great."'
>>> seg.segment(s)
['"I just love doing this sort of thing. It\'s great."']
>>> s = '"I phoned the \'Rape Helpline\' yesterday. They suggested I buy a balaclava."'
>>> seg.segment(s)
['"I phoned the \'Rape Helpline\' yesterday. They suggested I buy a balaclava."']
```

**Comment by ghnp5** [comment]
I wonder if we could have an option to change that behavior, as a parameter in the constructor? :)

**Comment by speedyk-005** [comment]
For users encountering this quote-segmentation limitation in pySBD, I'd recommend checking out **[Yasbd](https://github.com/speedyk-005/yasbd-lib)** — it's specifically designed to handle quoted text better.

Key differences:
- Yasbd has a `preserve_quote_and_paren=True` option (enabled by default) that respects quote boundaries
- **98.8% accuracy** on edge cases (vs pySBD's 84.5%) including complex quoted text, French abbreviations, Japanese dialog, and Spanish guillemets
- Pure Python, currently supports 5 languages (en, fr, es, ht, ja) but 22+ is the target

Example:
```python
from yasbd.boundary_detector import BoundaryDetector

detector = BoundaryDetector(lang="en", preserve_quote_and_paren=True)
result = detector.segment('"I just love doing this sort of thing. It\'s great."')
print(result)
# Output: ['"I just love doing this sort of thing. It\'s great."']
```

If you want drop-in pySBD compatibility, there's also an adapter:
```python
from yasbd.utils.pysbd_adapter import Segmenter

seg = Segmenter(language="en")
```

Full benchmarks comparing 7 SBD libraries: https://github.com/speedyk-005/yasbd-lib/tree/main/benchmarks
