### ISSUE TITLE
Looses text when breaking into sentences

### ISSUE THREAD

**Issue by ghost** [nipunsadvilkar/pySBD#57]
I did some very simple testing and found that the sentence parser dropping entire parts of the document when identifying the sentences.  The data is public so I can share it and a simple test driver.
But if you look at the output of sentences, you can see that about 1/2 the document is not returned in the sentences iterable in spacy.

`from pysbd.utils import PySBDFactory
import spacy

doc1 = 'EX-10.46 3 f18180exv10w46.htm EXHIBIT 10.46 exv10w46\n\n' \
'EXHIBIT 10.46\n\n'\
'Guarantee Agreement\n\n' \
'December 16, 2005\n\n' \
'SanDisk Corporation\n\n' \
'IBJ Leasing Co., Ltd.\n'\
'Sumisho Lease Co., Ltd.\n\n'\
'Toshiba Finance Corporation\n\n'\
'Guarantee Agreement\n\n'\
'SanDisk Corporation (the “Guarantor”) and IBJ Leasing Co., Ltd., Sumisho Lease Co., Ltd., and Toshiba Finance Corporation as SD Lessor thereunder (in such capacity, collectively, the “SD Lessors”) hereby enter into this guarantee agreement (the “Agreement”) with respect to the Master Lease Agreement dated December 16, 2005 and individual agreements thereunder (collectively, the “Lease Agreement”) by and between the SD Lessors and IBJ Leasing Co., Ltd. and Sumisho Lease Co., Ltd. as Toshiba Lessor thereunder (in such capacity, collectively, the “Toshiba Lessors”) and Flash Partners Yugen Kaisha (the “Lessee”).\n'\
'Unless as otherwise specified in this Agreement, the words defined in the Lease Agreement shall have the same meaning in this Agreement.\n\n'\
'Article 1. (Guarantee)\n\n'\
'The Guarantor shall guarantee the performance, from time to time, of the obligations subject to the guarantee below (the “Guaranteed Obligation”) to the SD Lessors, jointly and severally (rentai-hosho) with the Lessee (the “Guarantee”).\n\n'
'(Guaranteed Obligation)\n\n' \
'Guaranteed Obligation shall mean payment obligations of lease (lease-ryo), stipulated loss payment (kitei-songaikin), purchase option exercise price (konyu-sentakuken-koshikagaku), terminal return adjustment amount (henkanji-choseikin), break funding cost, late charges (chien-songaikin), and any and all payment obligations of other amounts concerning SD Tranche I and SD Tranche II in individual transactions pursuant to the Lease Agreement; provided that the Guarantor and the SD Lessors may consult in the event of any doubt concerning “other amounts” as mentioned above.\n\n' \
'In any event, the Guarantor shall not pay any obligation concerning Toshiba Tranche 1 and Toshiba Tranche 2.\n\n' \
'Article 2. (Period of Request for the Performance of Guarantee Obligation)\n\n'\
'In the event the SD Lessors request the performance of the Guarantee to the Guarantor, the SD Lessors shall make a written demand to the Guarantor requesting the performance of the Guaranteed Obligation which the Lessee fails to duly and punctually perform. The SD Lessors may, upon each failure of due and punctual performance of the Guaranteed Obligation, make a request pursuant to this Article; provided that the delay in making such request will not exempt the Guarantor from the obligations under the Guarantee.\n\n'\
'Article 3. (Performance of Guaranteed Obligation)\n\n'\
'3.1 The Guarantor shall, in the event the Lessee fails to perform all or any part of its obligations under the Guaranteed Obligation within 10 business days from each due date, perform the Guarantee in favor of the SD Lessors within 20 business days from the receipt of the written demand from the SD Lessors.'

nlp = spacy.blank('en')
nlp.add_pipe(PySBDFactory(nlp))

doc = nlp(doc1)

for num, sent in enumerate(doc.sents):
    print(f'{num} :  {sent}')`

**Comment by nipunsadvilkar** [comment]
Must be due to #55. Will be fixed in #63 
Feel free to reopen if the issue persists
