### ISSUE TITLE
Long number stalls process.

### ISSUE THREAD

**Issue by mollerhoj** [nipunsadvilkar/pySBD#58]
>>> t = 'Rok bud.2027777983834843834843042003200220012000199919981997199619951994199319921991199019891988198042003200220012000199919981997199619951994199319921991199019891988198'
>>> segmenter.segment(t)

Stalls. Apparently `replace_periods_before_numeric_references` takes forever.

**Comment by nipunsadvilkar** [comment]
Thanks for reporting. It was due to [Catastrophic Backtracking](http://www.regular-expressions.info/catastrophic.html) in `NUMBERED_REFERENCE_REGEX`
