### ISSUE TITLE
Example on website is broken

### ISSUE THREAD

**Issue by cranedroesch** [nipunsadvilkar/pySBD#72]
https://spacy.io/universe/project/python-sentence-boundary-disambiguation

<img width="288" alt="image" src="https://user-images.githubusercontent.com/13458532/88220310-cf802600-cc30-11ea-91f1-a054f1151cc7.png">

It should be `from pysbd.utils import PySBDFactory`, with an "s" on "utils"

**Comment by nipunsadvilkar** [comment]
will be fixed in https://github.com/explosion/spaCy/pull/5821
