### ISSUE TITLE
How to modify segmentation rules by hand?

### ISSUE THREAD

**Issue by anferico** [nipunsadvilkar/pySBD#90]
I have the following piece of text which I feed to pysbd.Segmenter:
```
'Trying to get back to Com. & Adm. through the most direct path in the dark.'
```
The correct way of handling this text is to keep it as a single sentence, although the `segment()` method returns:
```
['Trying to get back to Com.',
 '& Adm.',
 'through the most direct path in the dark.']
```

How do I tell the segmenter to avoid splitting a sentence at specific abbreviations, in this case "Com." and "Adm"? The poster in the README file states that rules are "easy to modify", so how do I do that?

**Comment by nipunsadvilkar** [comment]
You would need to tweak `Abbreviation` class and populate your keywords
within it.

**Comment by ywang4** [comment]
Hello, could you provide a more detailed tutorial for how to add custom rules? Thank you!

**Comment by garyhsu29** [comment]
Same question here, does anyone knows how to add the rule to Abbreviation?

**Comment by speedyk-005** [comment]
@anferico [yasbd-lib](https://github.com/speedyk-005/yasbd-lib) support that natively: https://github.com/speedyk-005/yasbd-lib#-lang-packs-api
